/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.6.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(libs.slick) {
        // The game ships its own LWJGL (lib/lwjgl.jar); Maven's 2.9.3 reports a
        // broken window size (0x256) on modern Windows, which breaks all projections.
        exclude(group = "org.lwjgl.lwjgl")
    }
    implementation(files("libs/lwjgl.jar", "libs/lwjgl_util.jar"))
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "game.Main"
}

tasks.named<JavaExec>("run") {
    jvmArgs(
        "-Djava.library.path=${project.rootDir}/native/windows",
        "-Dsun.java2d.d3d=false"
    )

    args(
        "-param",
        "-path:./_FarSky/",
        "-logPath:./_FarSky/log/",
        "-windowMode"
    )
}

tasks.withType<JavaCompile> { options.encoding = "UTF-8" }
